const boxShadowValue = "0px 3px 8px #00000027";

const Modern = [
  {
    themeTitle: "Tan",
    buttonBackgroundColor: "#8a8a8a",
    borderColor: "red",
    backgroundColor: "black",
    profileTextColor: "white",
    buttonTextColor: "white",
    buttonBorderRadius: "18px",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
  },
  {
    themeTitle: "Sea",
    buttonBackgroundColor: "#007bff",
    borderColor: "red",
    backgroundColor: "black",
    buttonTextColor: "white",
    buttonBorderRadius: "18px",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
    bottomNavButtonColor: "#384E81",
  },
  {
    themeTitle: "Sea",
    buttonBackgroundColor: "#54FF10",
    borderColor: "red",
    backgroundColor: "black",
    buttonTextColor: "black",
    buttonBorderRadius: "18px",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
    bottomNavButtonColor: "#384E81",
  },
  {
    themeTitle: "Sea",
    buttonBackgroundColor: "#FF8700",
    borderColor: "red",
    backgroundColor: "black",
    buttonTextColor: "white",
    buttonBorderRadius: "18px",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
    bottomNavButtonColor: "#384E81",
  },
  {
    themeTitle: "Tan",
    buttonBackgroundColor: "black",
    // border: "2px solid #8a8a8a",
    borderColor: "red",
    backgroundColor: "#8a8a8a",
    profileTextColor: "white",
    buttonTextColor: "white",
    buttonBorderRadius: "18px",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
  },

  {
    themeTitle: "Sea",
    buttonBackgroundColor: "#245442",
    borderColor: "red",
    backgroundColor: "#8a8a8a",
    buttonTextColor: "white",
    buttonBorderRadius: "18px",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: "Poppins",
    bottomNavButtonColor: "#384E81",
  },
];

export default Modern;
