const boxShadowValue = "0px 3px 8px #00000027";

const gradientDefaultFont = "Poppins";

const Primary = [
  {
    themeTitle: "Snow",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    backgroundColor: "black",
    buttonTextColor: "black",
    profileTextColor: "white",
    bottomNavButtonColor: "#957BF0",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Sea",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    buttonTextColor: "#FECE2D",
    backgroundColor: "#FECE2D",
    profileTextColor: "white",
    bottomNavButtonColor: "#E2A2DC",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Olive",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    buttonTextColor: "#6600db",
    backgroundColor: "#6600db",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Olive",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    buttonTextColor: "#00cc3d",
    backgroundColor: "#00cc3d",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Olive",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    buttonTextColor: "#e6151f",
    backgroundColor: "#e6151f",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Olive",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    border: "2px solid white",
    borderColor: "white",
    buttonTextColor: "#384cff",
    backgroundColor: "#384cff",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
  {
    themeTitle: "Olive",
    buttonBackgroundColor: "white",
    buttonBorderRadius: "10px",
    borderColor: "white",
    border: "2px solid white",
    buttonTextColor: "#fb2bff",
    backgroundColor: "#fb2bff",
    profileTextColor: "white",
    boxShadow: `${boxShadowValue}`,
    fontFamily: `${gradientDefaultFont}`,
  },
];

export default Primary;
